<?php

declare(strict_types=1);

namespace Techork\PaymentService\Common\ValueObject\Risk;

/**
 * Normalized result of a single {@see \Techork\PaymentService\Common\Contract\FraudScreeningProvider}
 * screening. Adapters map their provider-specific response onto this shape so
 * the decision layer stays vendor-agnostic.
 *
 * `reference` is the provider's own transaction/verification identifier when
 * one is returned; the fraud reference forwarded downstream (the value
 * persisted as `fraud_id` / `fraudPrevention.uuid`) is generated by the caller
 * and is distinct from this.
 */
final readonly class FraudVerdict
{
    public function __construct(
        public FraudDecision $decision,
        public ?string $reasonCode = null,
        public ?string $reference = null,
    ) {}

    public function isApproved(): bool
    {
        return $this->decision === FraudDecision::Approve;
    }

    public function isDeclined(): bool
    {
        return $this->decision === FraudDecision::Decline;
    }

    /**
     * True when the screening produced no usable verdict — either the provider
     * declined to review the transaction or the call failed. Callers use this
     * to apply their fail-open / fail-closed policy.
     */
    public function isInconclusive(): bool
    {
        return $this->decision === FraudDecision::NotReviewed
            || $this->decision === FraudDecision::Errored;
    }
}
